add support for time.duration[WIP]
beatlabs/harvester pull request #65
Opened 2020-09-05 17:18 UTC by YafimK

## Which problem is this PR solving?
Allow usage of time.Duration as field

## Short description of the changes
Mainly adding the time.Duration as cfg type implemented interface.

2020-09-08 07:23 UTC, mantzas requested changes

2020-09-08 07:23 UTC, mantzas commented on sync/sync.go
> +func (s *TimeDuration) Get() time.Duration {
As codecov mentioned maybe we should write some unit tests to cover the methods for TimeDuration.

2020-09-08 08:14 UTC, mantzas approved these changes

2020-09-08 09:06 UTC, c0nstantx commented on harvester_integration_test.go
> +		`INFO: automatically monitoring consul key "harvester/FunTime"`,
Maybe try keeping the keys consistent for readability and not use camel case (`harvester/fun-time`)

2020-09-09 08:57 UTC, mantzas submitted a review, later dismissed

2020-09-09 09:00 UTC, c0nstantx approved these changes

2020-09-09 09:04 UTC, mantzas commented
@YafimK there is a data race in the tests can you check?

2020-09-10 06:23 UTC, mantzas approved these changes

2020-09-10 07:22 UTC, c0nstantx submitted a review, later dismissed

2020-09-10 07:28 UTC, Lazaros-Tsigkakos approved these changes

2020-10-31 13:42 UTC, mantzas commented
@YafimK Sorry letting this fall through the cracks. On last request. Can you also update the Readme to reflect the new data type added?

2020-11-08 09:31 UTC, mantzas approved these changes

2020-11-08 09:32 UTC, c0nstantx approved these changes

2020-11-08 11:03 UTC, Lazaros-Tsigkakos approved these changes

2020-11-08 11:51 UTC, merged